# Generated by Django 4.2.5 on 2023-12-20 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('is_mentor', models.BooleanField(default=False)),
                ('is_sponsor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('necessary_links', models.URLField()),
                ('funds_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mentors', models.ManyToManyField(blank=True, related_name='mentored_projects', to='ideavault.contributor')),
                ('sponsors', models.ManyToManyField(blank=True, related_name='sponsored_projects', to='ideavault.contributor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to='ideavault.student')),
            ],
        ),
    ]
